---
sidebar: sidebar 
permalink: task_adding_permissions_to_service_accounts.html 
keywords: netapp, saas backup, microsoft 365, add, adding, permissions, service, accounts 
summary: Se necessário, você pode adicionar contas adicionais para melhorar o desempenho do backup. As contas de serviço são usadas para executar backups simultâneos com eficiência. 
---
= Adicione contas de serviço adicionais
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se necessário, você pode adicionar contas de serviço adicionais para melhorar o desempenho do backup. As contas de serviço são usadas para executar backups simultâneos com eficiência.

.Passos
. Inicie sessão no Portal de Gestão do Microsoft 365 utilizando uma conta com Privileges administrativo.
. Clique no ícone do lançador de aplicativos e, em seguida, clique em *Admin*.
. À esquerda, clique em *Users* (usuários) e depois em *ative Users* (usuários ativos).
. Clique em *Adicionar um usuário* para criar uma nova conta.
. Preencha o formulário seguindo as instruções abaixo.
+
** Use *deixe-me criar a senha*.
** Desmarque *Faça com que este usuário altere sua senha quando ele entrar pela primeira vez* opção.
** Selecione a função *Administrador Personalizado*.
** Selecione *administrador do Exchange* e *administrador do SharePoint*.
** Selecione *criar usuário sem licença de produto*.


. Para que os backups do Exchange sejam executados com contas de serviço recém-criadas, atribua os direitos de representação do Exchange a essas contas de serviço recém-criadas. link:task_configuring_impersonation.html["Configurando personificações"]



NOTE: O backup do SaaS atribui automaticamente as permissões nos sites do OneDrive e do SharePoint, para que você não precise atribuí-las.


NOTE: Você pode habilitar a autorização multifator (MFA) nessa conta.
